const formConfig = {
  FormTypes: {
    Section: {
      id: "0",
      Placeholder: "",
      Default_Value: "Section",
      Required: "false",
      Readonly: "false",
      Visible: "true",
      label: "New Section",
      children: [], 
    },
    Text: {
      id: "0",
      Placeholder: "Enter Value",
      Default_Value: "Text",
      Required: "false",
      Readonly: "false",
      Visible: "true",
      label: "Text Field",
    },
    TextArea: {
      id: "0",
      Placeholder: "Enter Value",
      Default_Value: "TextArea",
      Required: "false",
      Readonly: "false",
      Visible: "true",
      label: "Text Area",
    },
    Number: {
      id: "0",
      Placeholder: "Enter Value",
      Default_Value: "Number",
      Required: "false",
      Readonly: "false",
      Visible: "true",
      label: "Number",
    },
    Dropdown: {
      id: "0",
      Placeholder: "Select Option",
      Default_Value: "Dropdown",
      Required: "false",
      Readonly: "false",
      Visible: "true",
      label: "Dropdown",
    },
    MultiSelect: {
      id: "0",
      Placeholder: "Select individuals",
      Default_Value: "MultiSelect",
      Required: "false",
      Readonly: "false",
      Visible: "true",
      label: "Multi Select",
    },
    Radio: {
      id: "0",
      Placeholder: "Select Option",
      Default_Value: "Radio",
      Required: "false",
      Readonly: "false",
      Visible: "true",
      label: "Radio",
    },
    Checkbox: {
      id: "0",
      Placeholder: "Check options",
      Default_Value: "Checkbox",
      Required: "false",
      Readonly: "false",
      Visible: "true",
      label: "Checkbox",
    },
    Date: {
      id: "0",
      Placeholder: "Select Date",
      Default_Value: "Date",
      Required: "false",
      Readonly: "false",
      Visible: "true",
      label: "Date",
    },
    DateTime: {
      id: "0",
      Placeholder: "Select Date Time",
      Default_Value: "DateTime",
      Required: "false",
      Readonly: "false",
      Visible: "true",
      label: "Date Time",
    },
    FileUpload: {
      id: "0",
      Placeholder: "Upload File",
      Default_Value: "FileUpload",
      Required: "false",
      Readonly: "false",
      Visible: "true",
      label: "File Upload",
    },
    Lookup: {
      id: "0",
      Placeholder: "Search...",
      Default_Value: "Lookup",
      Required: "false",
      Readonly: "false",
      Visible: "true",
      label: "Lookup",
    },
    Table: {
      id: "0",
      Placeholder: "Enter Data",
      Default_Value: "Table",
      Required: "false",
      Readonly: "false",
      Visible: "true",
      label: "Table",
    },
    Repeater: {
      id: "0",
      Placeholder: "",
      Default_Value: "Repeater",
      Required: "false",
      Readonly: "false",
      Visible: "true",
      label: "Repeater",
    },
    ColorPicker: {
      id: "0",
      Placeholder: "Pick Color",
      Default_Value: "ColorPicker",
      Required: "false",
      Readonly: "false",
      Visible: "true",
      label: "Color Picker",
    },
    Label: {
      id: "0",
      Placeholder: "Label Text",
      Default_Value: "Label",
      Required: "false",
      Readonly: "false",
      Visible: "true",
      label: "Label",
    },
    Signature: {
      id: "0",
      Placeholder: "Sign Here",
      Default_Value: "Signature",
      Required: "false",
      Readonly: "false",
      Visible: "true",
      label: "Signature",
    },
    ComputedFields: {
      id: "0",
      Placeholder: "Computed Result",
      Default_Value: "ComputedFields",
      Required: "false",
      Readonly: "false",
      Visible: "true",
      label: "Computed",
    },
    HiddenFields: {
      id: "0",
      Placeholder: "Hidden Value",
      Default_Value: "HiddenFields",
      Required: "false",
      Readonly: "false",
      Visible: "true",
      label: "Hidden",
    },
  },
};
export default formConfig;